### ISSUE TITLE
安全验证失败

### ISSUE THREAD

**Issue by jun9100** [NolanHzy/nvjdcdocker#18]
System.MissingMethodException: Method not found: 'System.Threading.Tasks.Task PageMove.PageMove.Move(PuppeteerSharp.Page, Int32, Int32)'.
   at Server.PageServer.PageServer.AutoCaptcha(String Phone)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Server.PageServer.PageServer.AutoCaptcha(String Phone)
   at NETJDC.Controllers.CloudController.AutoCaptcha(RequestEntity obj) in E:\03工作源码\NETJDC\NETJDC\Controllers\CloudController.cs:line 117
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by NolanHzy** [comment]
你不在频道？明天等我更新，少提交了文件

**Comment by y162287761** [comment]
> 你不在频道？明天等我更新，少提交了文件

请问频道多少

**Comment by jun9100** [comment]
请问频道地址。
