### ISSUE TITLE
手机获取验证码后没有报错，只有JSHandle:getMsg-btn text-btn J_ping timer active

### ISSUE THREAD

**Issue by 330377782** [NolanHzy/nvjdcdocker#24]
手机获取验证码后没有报错，只有JSHandle:getMsg-btn text-btn J_ping timer active

**Comment by l123456789jy** [comment]
System.Exception: 请输入手机号码
   at NETJDC.Controllers.CloudController.VerifyCode(RequestEntity obj) in E:\03工作源码\NETJDC\NETJDC\Controllers\CloudController.cs:line 393
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
JSHandle:getMsg-btn text-btn J_ping timer active
[?1h=PuppeteerSharp.PuppeteerException: Protocol error (Runtime.evaluate): Session closed. Most likely the Page has been closed.Close reason: Target.detachedFromTarget
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 166
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\CDPSession.cs:line 118
   at PuppeteerSharp.ExecutionContext.ExecuteEvaluationAsync(String method, Object args) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 182
   at PuppeteerSharp.ExecutionContext.RemoteObjectTaskToObject[T](Task`1 remote) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\ExecutionContext.cs:line 136
   at PuppeteerSharp.DOMWorld.EvaluateExpressionAsync[T](String script) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\DOMWorld.cs:line 89
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.WaitSendSms(Page page, Boolean debug) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 469
   at Server.PageServer.PageServer.OpenJDTab(Int32 qlkey, String Phone, Boolean UploadQL) in E:\03工作源码\NETJDC\Server\PageServer\PageServer.cs:line 338
   at NETJDC.Controllers.CloudController.SendSMS(RequestEntity obj) in E:\03工作源码\NETJDC\NETJDC\Controllers\CloudController.cs:line 136

**Comment by xblvesting** [comment]
同样的问题，日志里只有JSHandle:getMsg-btn text-btn J_ping timer active，网页登录不进去

**Comment by 330377782** [comment]
换成家用IP就好了，京东对服务器IP做了限制

**Comment by 5axf** [comment]
> 换成家用IP就好了，京东对服务器IP做了限制

轻量服务器gg，换不了ip

**Comment by drophair** [comment]
> > 换成家用IP就好了，京东对服务器IP做了限制
> 
> 轻量服务器gg，换不了ip

你可以在家里的服务器上搭建,一步到位不需要续费,配置自定义,可玩性更高,云服务器用于产品部署场景。
这种东西更加适合在本地运行,相对来说会比较安全。
