### ISSUE TITLE
1.2版运行出错

### ISSUE THREAD

**Issue by lukemin** [NolanHzy/nvjdcdocker#4]
<html>
<body>

date | stream | content
-- | -- | --
2021-11-14 16:06:00 | stdout | * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.[39;49m
2021-11-14 16:06:00 | stdout | * You intended to execute a .NET program, but dotnet-NETJDC.dll does not exist.
2021-11-14 16:06:00 | stdout | * You misspelled a built-in dotnet command.
2021-11-14 16:06:00 | stdout | Possible reasons for this include:
2021-11-14 16:06:00 | stdout | [39;49m[?1h=[31mCould not execute because the specified command or file was not found.

</body>
</html>

**Comment by dhlsam** [comment]
1.3版本 填完ql 名称 | Client ID | Client Secret
重启后显示 配置有误获取token失败

___ ________ ________
|\ \|\ ___ \|\ ____\
\ \ \ \ \ |\ \ \ \___ |
__ \ \ \ \ \ \\ \ \ \
|\ \\_\ \ \ \_\\ \ \ \____
\ \________\ \_______\ \_______\
\| ________|\| ______|\| ______|


By Nolan


初始化项目
第一次运行会下载Chromium,后续只是检查是否下载
检查中....
True
检查成功
程序配置自检
如果报错请检查配置或者检查配置是否挂载


--------------------------------------------------------
版本:1.3
上传模式：ql
回收时间：3分钟
自动滑块：5
--------------------------------------------------------
NETJDC started
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Now listening on: http://[::]:80
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Application started. Press Ctrl+C to shut down.
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Hosting environment: Production
[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
Content root path: /app
System.Exception: 配置有误获取token失败
at Systems.Qlconfig.GetToken() in E:\03工作源码\NETJDC\Systems\MainConfig.cs:line 149
at Systems.Qlconfig.GetEnv(String searchValue) in E:\03工作源码\NETJDC\Systems\MainConfig.cs:line 157
at Systems.Qlconfig.GetEnvsCount(String searchValue) in E:\03工作源码\NETJDC\Systems\MainConfig.cs:line 186
at NETJDC.Controllers.CloudController.Config() in E:\03工作源码\NETJDC\NETJDC\Controllers\CloudController.cs:line 59
at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)

at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

**Comment by lukemin** [comment]
群晖上需要安装git server， 运行git命令后才能使用，但是需要根据教程修改 
git clone https://ghproxy.com/https://github.com/NolanHzy/nvjdcdocker.git 修改你自己为nolanjdc选定的文件夹。
mount 的文件夹也需要修改  nolanjdc选定的文件夹 /app

**Comment by lukemin** [comment]
> 1.3版本 填完ql 名称 | Client ID | Client Secret 重启后显示 配置有误获取token失败
> 
> |\ |\ ___ |\ __** \ \ \ \ \ |\ \ \ _** | __ \ \ \ \ \ \ \ \ |\ \_\ \ \ _\ \ \ ____ \ __******\ _******\ _______ | ________|| ______|| ______|
> 
> By Nolan
> 
> 初始化项目 第一次运行会下载Chromium,后续只是检查是否下载 检查中.... True 检查成功 程序配置自检 如果报错请检查配置或者检查配置是否挂载
> 
> ## 版本:1.3
> 上传模式：ql
> 回收时间：3分钟
> 自动滑块：5
> NETJDC started �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0] Now listening on: http://[::]:80 �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0] Application started. Press Ctrl+C to shut down. �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0] Hosting environment: Production �[40m�[32minfo�[39m�[22m�[49m: Microsoft.Hosting.Lifetime[0] Content root path: /app System.Exception: 配置有误获取token失败 at Systems.Qlconfig.GetToken() in E:\03工作源码\NETJDC\Systems\MainConfig.cs:line 149 at Systems.Qlconfig.GetEnv(String searchValue) in E:\03工作源码\NETJDC\Systems\MainConfig.cs:line 157 at Systems.Qlconfig.GetEnvsCount(String searchValue) in E:\03工作源码\NETJDC\Systems\MainConfig.cs:line 186 at NETJDC.Controllers.CloudController.Config() in E:\03工作源码\NETJDC\NETJDC\Controllers\CloudController.cs:line 59 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
> 
> at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted) at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

把文件夹的名字换成英文的试一下。
