### ISSUE TITLE
报错‘Value cannot be null. (Parameter 's')’

### ISSUE THREAD

**Issue by bingoIsCoder** [NolanHzy/nvjdcdocker#45]
打开页面报错，请问下是什么原因呢：

System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at System.Int32.Parse(String s)
   at NETJDC.Controllers.CloudController.Config() in E:\03工作源码\NETJDC\NETJDC\Controllers\CloudController.cs:line 83
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()

**Comment by bingoIsCoder** [comment]
找到原因了不好意思，config.json 第一个字母大写 Config.json，谢谢仓主

**Comment by lplbb** [comment]
> 找到原因了不好意思，config.json 第一个字母大写 Config.json，谢谢仓主

文件下没有config.json是不是要自己导入这个文件
